{
 "title": "AWS Darkdata Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": "# Visualisierung von Dark Data in AWS"
   }
  },
  {
   "title": "Kohlenstoffintensität des Strommixes in gCO₂eq/kWh in Deutschland",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "electricity_maps{attr=\"CarbonIntensity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Anwendungsfall #1 - S3 Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Anteil Dark Data in S3 Bucket ",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "s3_old_files_size_bytes", "legendFormat": "Anteil Dark Data" },
    { "expr": "s3_new_files_size_bytes", "legendFormat": "Gesamtgröße der Daten" }
   ]
  },
  {
   "title": "CO2-Emissionen S3 Bucket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "s3_old_files_size_bytes{bucket=\"studiumtest\"} / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "Dark Data (TiB)"
    },
    {
     "expr": "sum(s3_old_files_size_bytes{bucket=\"studiumtest\"} / 1099511627776 * 1.52)",
     "legendFormat": "Energieverbrauch in Wh"
    },
    { "expression": "$Wh /1000 * $Carbon", "type": "math" }
   ]
  },
  {
   "title": "Anwendungsfall #2 - Veraltete Datensätze",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Anteil veralteter Datensätzen in Rental-Tabelle",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aurora_metadata{table=\"rental\", attr=\"alte_eintraege\"}",
     "legendFormat": "Veraltete Einträge (Dark Data)"
    },
    {
     "expr": "aurora_metadata{table=\"rental\", attr=\"gesamt_anzahl\"}",
     "legendFormat": "Gesamten Einträge"
    }
   ]
  },
  {
   "title": "CO2-Emissionen Aurora veraltete Datensätze",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aurora_metadata{table=\"rental\", attr=\"alte_bytes\"} / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "Veraltete Datensätze (TiB)"
    },
    {
     "expr": "sum(aurora_metadata{attr=\"total_size_in_bytes\", table=\"rental\"} / 1099511627776 * 1.52)",
     "legendFormat": "Energieverbrauch in Wh"
    },
    { "expression": "$Wh / 1000 * $carbon_intensity", "type": "math" }
   ]
  },
  {
   "title": "Anwendungsfall #3 - Duplizierte Adressen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Anteil der Duplikate in der Address-Tabelle",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aurora_metadata{attr=\"doppelte_eintraege\", table=\"address\"}",
     "legendFormat": "Duplizierte Einträge"
    },
    {
     "expr": "aurora_metadata{attr=\"einzigartige_eintraege\", table=\"address\"}",
     "legendFormat": "Einzigartige Einträge"
    }
   ]
  },
  {
   "title": "CO2-Emissionen Aurora Duplikate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aurora_metadata{attr=\"doppelte_bytes\"} / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "Duplikate (TiB)"
    },
    {
     "expr": "sum(aurora_metadata{attr=\"doppelte_bytes\", table=\"address\"} / 1099511627776 * 1.52)",
     "legendFormat": "Energieverbrauch in Wh"
    },
    { "expression": "$wh / 1000 * $carbon_intensity", "type": "math" }
   ]
  }
 ]
}